### ISSUE TITLE
Refactor preprocessors to callables

### ISSUE THREAD

**Issue by jmcarp** [eregs/regulations-parser#192]
The `PreProcessorBase` is an abstract base class that defines a single abstract method, `transform`. Since instances of its concrete subclasses don't have any state, this is a good case for a refactor into plain functions, or callable classes if necessary. This isn't urgent or even strictly necessary, since the code is perfectly readable as-is, but simpler code with minimal indirection is always nice.

For your consideration: https://www.youtube.com/watch?v=o9pEzgHorH0

**Comment by cmc333333** [comment]
Resolved with #342
