### ISSUE TITLE
Move tests dir into regparser

### ISSUE THREAD

**Issue by cmc333333** [eregs/regulations-parser#214]
We've had the `tests` module in the root of the repository for some time. We should move that into `regparser.tests` to

1. be better namespace stewards
2. follow best practices
3. be reusable for plugins

**Comment by jmcarp** [comment]
Whose best practices? Most libraries that I've seen keep source and tests in separate top-level directories.

**Comment by cmc333333** [comment]
Keeping the test directory in the root is fine _if no one will reuse it_. However, we would like to allow projects which use `regparser` as a library to also have access to helper functions, etc. from the current `tests` namespace. Even within the `regparser` tests, it's super weird to import something from the global `tests` module.

**Comment by jmcarp** [comment]
If plugins are going to want to import from tests, then cool. This just activated my best-practices sense because python tests are (in my experience) rarely non-top level, including in libraries that are meant to be reused.

**Comment by tadhg-ohiggins** [comment]
Currently the extension tests do import from tests so as to not have to duplicate code, and have lines like `from tests.xml_builder import XMLBuilderMixin`, which certainly looks fragile. Also, this comment is a reminder that when we do this, the extension tests (of which there are only currently a couple) will break.

**Comment by cmc333333** [comment]
What if we just moved the _shared_ test stuff into `regparser`? I thought I knew where tests are supposed to go, but @jmcarp's research disproved that.

**Comment by tadhg-ohiggins** [comment]
That makes sense to me. How hard will it be to separate the shared test stuff from the rest?

**Comment by cmc333333** [comment]
@tadhg-ohiggins shouldn't be too hard -- I think we only have two shared test modules: xml_builder and node_accessor. We can verify by checking for `from tests import`.

**Comment by cmc333333** [comment]
Resolved now!
