### ISSUE TITLE
Docker Hub build is failing

### ISSUE THREAD

**Issue by gregoryfoster** [eregs/regulations-parser#360]
Hello, I just noticed that the Docker Hub build for [`eregs/parser`](https://hub.docker.com/r/eregs/parser) is currently failing:
[https://hub.docker.com/r/eregs/parser/builds/bdkmamcgqpjkznw2qq6duxk/](https://hub.docker.com/r/eregs/parser/builds/bdkmamcgqpjkznw2qq6duxk/)

```bash
[91minterpparser should either be a path to a local project or a VCS url beginning with svn+, git+, hg+, or bzr+
[0m
Removing intermediate container a55071fe2e8f

Build failed: The command '/bin/sh -c apk add --update libxslt libxml2-dev libxslt-dev musl-dev gcc git && pip install --no-cache-dir -r requirements.txt && apk del --purge libxml2-dev libxslt-dev musl-dev gcc && rm -rf /var/cache/apk/*' returned a non-zero code: 1
```

It looks like it's been consistently failing since Dec 27 (2016-12-27T04:06:23.722Z), not sure which `eregs/regulations-parser` commit, whatever was `latest` as of that build timestamp:
[https://hub.docker.com/r/eregs/parser/builds/b7badg8av3qet7bjesygfkb/](https://hub.docker.com/r/eregs/parser/builds/b7badg8av3qet7bjesygfkb/)

**Comment by cmc333333** [comment]
Thanks for finding this! We'll fix and add a docker-build test to our CI.
