### ISSUE TITLE
Minor documentation updates for eregs clear command

### ISSUE THREAD

**Issue by gregoryfoster** [eregs/regulations-parser#361]
While reviewing the behavior of the `eregs clear` command, I noticed two minor documentation updates that can be made.

When running `eregs clear --help`, I believe the following output refers to a regulation part rather than title on [`clear.py`:19](https://github.com/eregs/regulations-parser/blob/master/regparser/commands/clear.py#L19):

```bash
$ eregs clear diff/27 trees     # deletes all cached trees and all CFR
                                # title 27 diffs
```

And in the ["Parsing New Rules" documentation's "Fetching the Rule" section](https://eregs-parser.readthedocs.io/en/latest/new_rules.html#fetching-the-rule), there's mention of a `--http-cache` parameter which does not look like it's recognized anymore.  It looks like the `http_client`'s cache is always cleared on [`clear.py`:31](https://github.com/eregs/regulations-parser/blob/master/regparser/commands/clear.py#L31).

I'll return to this and put together a pull request.

**Comment by cmc333333** [comment]
Good point about `http_cache`! Regarding title vs. part, diffs are currently stored in a directory-like structure of `diff / <cfr title> / <cfr part> / <left version> / <right version>`, so I think "title" is correct.

Heads up that the way all of that is stored will be changing soon(-ish) as part of #356. We had a file-system based system for quite a while but are migrating to using Django's models (including proper foreign key dependencies), which should make a lot of this code easier to understand.

**Comment by gregoryfoster** [comment]
Thanks for the quick response, @cmc333333.  My bad re: diff directory structure, I was looking at the `output` directory structure rather than paths in `.eregs_index`.  And thanks for the heads up re: #356.

**Comment by gregoryfoster** [comment]
Doc update is in PR #363.

**Comment by cmc333333** [comment]
#363 resolved, thanks again!
